<?php

namespace Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class EzMageB2BMongoDBDocumentPriceHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['customer_code'])) {
            $value = $data['customer_code'];
            $return = (string) $value;
            $this->class->reflFields['customerCode']->setValue($document, $return);
            $hydratedData['customerCode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['product_sku'])) {
            $value = $data['product_sku'];
            $return = (string) $value;
            $this->class->reflFields['productSku']->setValue($document, $return);
            $hydratedData['productSku'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['price'])) {
            $value = $data['price'];
            $return = (float) $value;
            $this->class->reflFields['price']->setValue($document, $return);
            $hydratedData['price'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['tier_price'])) {
            $value = $data['tier_price'];
            $return = $value;
            $this->class->reflFields['tierPrice']->setValue($document, $return);
            $hydratedData['tierPrice'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['updated_at'])) {
            $value = $data['updated_at'];
            $return = (string) $value;
            $this->class->reflFields['updatedAt']->setValue($document, $return);
            $hydratedData['updatedAt'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['etc'])) {
            $value = $data['etc'];
            $return = (string) $value;
            $this->class->reflFields['etc']->setValue($document, $return);
            $hydratedData['etc'] = $return;
        }
        return $hydratedData;
    }
}